import '../styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from '@/components/header';
import Hero from '@/components/hero';
import List from '@/components/list'
import Content from '@/components/content';
import Contact from '@/components/contact';
import Testimonial from '@/components/testimonial';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Header />
        {children}
        <Hero />
        <List/>
        <Content/>
        <Contact/>
        <Testimonial/>
      </body>
    </html>
  );
}
